package com.exarlabs.android.slidingpuzzle.;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.exarlabs.android.slidingpuzzle..Solutions;

import com.exarlabs.android.slidingpuzzle..SolutionsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig solutionsDaoConfig;

    private final SolutionsDao solutionsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        solutionsDaoConfig = daoConfigMap.get(SolutionsDao.class).clone();
        solutionsDaoConfig.initIdentityScope(type);

        solutionsDao = new SolutionsDao(solutionsDaoConfig, this);

        registerDao(Solutions.class, solutionsDao);
    }
    
    public void clear() {
        solutionsDaoConfig.getIdentityScope().clear();
    }

    public SolutionsDao getSolutionsDao() {
        return solutionsDao;
    }

}
