package com.exarlabs.android.slidingpuzzle.;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SOLUTIONS".
 */
public class Solutions {

    private Long id;
    private int size;
    /** Not-null value. */
    private String steps;

    public Solutions() {
    }

    public Solutions(Long id) {
        this.id = id;
    }

    public Solutions(Long id, int size, String steps) {
        this.id = id;
        this.size = size;
        this.steps = steps;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getSize() {
        return size;
    }

    public void setSize(int size) {
        this.size = size;
    }

    /** Not-null value. */
    public String getSteps() {
        return steps;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSteps(String steps) {
        this.steps = steps;
    }

}
