package com.exarlabs.android.slidingpuzzle.model.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.exarlabs.android.slidingpuzzle.model.dao.GeneratedSolution;
import com.exarlabs.android.slidingpuzzle.model.dao.Play;

import com.exarlabs.android.slidingpuzzle.model.dao.GeneratedSolutionDao;
import com.exarlabs.android.slidingpuzzle.model.dao.PlayDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig generatedSolutionDaoConfig;
    private final DaoConfig playDaoConfig;

    private final GeneratedSolutionDao generatedSolutionDao;
    private final PlayDao playDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        generatedSolutionDaoConfig = daoConfigMap.get(GeneratedSolutionDao.class).clone();
        generatedSolutionDaoConfig.initIdentityScope(type);

        playDaoConfig = daoConfigMap.get(PlayDao.class).clone();
        playDaoConfig.initIdentityScope(type);

        generatedSolutionDao = new GeneratedSolutionDao(generatedSolutionDaoConfig, this);
        playDao = new PlayDao(playDaoConfig, this);

        registerDao(GeneratedSolution.class, generatedSolutionDao);
        registerDao(Play.class, playDao);
    }
    
    public void clear() {
        generatedSolutionDaoConfig.getIdentityScope().clear();
        playDaoConfig.getIdentityScope().clear();
    }

    public GeneratedSolutionDao getGeneratedSolutionDao() {
        return generatedSolutionDao;
    }

    public PlayDao getPlayDao() {
        return playDao;
    }

}
