package com.exarlabs.android.slidingpuzzle.model.dao;

import java.util.Map;

import android.database.sqlite.SQLiteDatabase;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig generatedSolutionDaoConfig;

    private final GeneratedSolutionDao generatedSolutionDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        generatedSolutionDaoConfig = daoConfigMap.get(GeneratedSolutionDao.class).clone();
        generatedSolutionDaoConfig.initIdentityScope(type);

        generatedSolutionDao = new GeneratedSolutionDao(generatedSolutionDaoConfig, this);

        registerDao(GeneratedSolution.class, generatedSolutionDao);
    }
    
    public void clear() {
        generatedSolutionDaoConfig.getIdentityScope().clear();
    }

    public GeneratedSolutionDao getGeneratedSolutionDao() {
        return generatedSolutionDao;
    }

}
