package com.exarlabs.android.slidingpuzzle.model.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GENERATED_SOLUTION".
 */
public class GeneratedSolution {

    private Long id;
    private int size;
    /** Not-null value. */
    private byte[] moves;

    public GeneratedSolution() {
    }

    public GeneratedSolution(Long id) {
        this.id = id;
    }

    public GeneratedSolution(Long id, int size, byte[] moves) {
        this.id = id;
        this.size = size;
        this.moves = moves;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getSize() {
        return size;
    }

    public void setSize(int size) {
        this.size = size;
    }

    /** Not-null value. */
    public byte[] getMoves() {
        return moves;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMoves(byte[] moves) {
        this.moves = moves;
    }

}
